### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ingmichi** [gesellix/titlelink#13]
Hello,

after installing titlelink I got an error message on the top of my page refering to line 187 in titlelink.php.

I tried to add a link - no problem - works!

Any ideas?

Michael

**Comment by gesellix** [comment]
on which Joomla version did you try it?

**Comment by ingmichi** [comment]
Joomla 2.5, deutsche Version vor ca. 14 Tagen herunter geladen.

lg

Michi

> -------- Original-Nachricht --------
> Datum: Wed, 05 Dec 2012 11:42:07 -0800
> Von: Tobias Gesellchen notifications@github.com
> An: gesellix/titlelink titlelink@noreply.github.com
> CC: ingmichi r.michael@gmx.net
> Betreff: Re: [titlelink] error (#13)

**Comment by gesellix** [comment]
wie lautete die Fehlermeldung?

**Comment by ingmichi** [comment]
Strict Standards: Only variables should be assigned by reference in 
C:\Programme\xampp\htdocs\plugins\system\titlelink\titlelink.php on line 
187

Schöne Grüße aus dem Wienerwald

Michael

> -------- Original-Nachricht --------
> Datum: Thu, 06 Dec 2012 09:38:57 -0800
> Von: Tobias Gesellchen notifications@github.com
> An: gesellix/titlelink titlelink@noreply.github.com
> CC: ingmichi r.michael@gmx.net
> Betreff: Re: [titlelink] error (#13)

**Comment by gesellix** [comment]
Merci! Die Infos reichen mir wahrscheinlich aus.
Danke für das Feedback und schöne Grüße aus Berlin :)
Tobias

**Comment by gesellix** [comment]
Kannst du die Anpassungen unter dem Branch https://github.com/gesellix/titlelink/tree/joomla_3_0 testen? Ich habe bisher nur minimale Änderungen vorgenommen und noch nicht ausreichend getestet. Allerdings scheint die Verlinkung defekt zu sein und falsche Ergebnisse zu liefern.

**Comment by gesellix** [comment]
@ingmichi hast du schon die letzten Änderungen testen können?

**Comment by gesellix** [comment]
Ich schließe dieses Ticket, anscheinend ist der Fehler behoben?!

Unabhängig davon ist ein Joomla 3.2 kompatibles Paket unter https://github.com/gesellix-joomla/titlelink/raw/develop/packages/plg_titlelink_2013-11-18_joomla3_2.zip verfügbar.

Falls noch Probleme auftreten, erstelle bitte ein neues Ticket unter https://github.com/gesellix-joomla/titlelink/issues

Danke!
