### ISSUE TITLE
Support for Joomla 3.0

### ISSUE THREAD

**Issue by rowby** [gesellix/titlelink#14]
HI 

I see this extension is work with Joomla 2.5.  Are there plans for a Joomla 3.x version?

Thanks

Rowby

**Comment by gesellix** [comment]
Well, as usual I don't expect many changes to be implemented for a compatibility to Joomla 3.x. I actually had a quick look at a local Joomla installation. But due to the lack of time I don't know how fast I can reach a working state for Joomla 3.0. Would it be possible for you to support me when it comes to testing in a real life environment?

**Comment by rowby** [comment]
Sure.  Will be happy troubleshoot the extension for you.  I do that now and
then and will be happy to do that for you.

Rowby

**Comment by tripslip38** [comment]
Has there been any progress on the Joomla 3.0 branch? It seems there hasn't been any commits in a while. How can i help?

**Comment by gesellix** [comment]
@tripslip38 as you already did: you can help me with testing on a real life page. I will have a look at your test result and try to fix it asap. I guess at the end of next week I can get some time for this.
Sorry for the lack of activity... life and such is sometimes more important, you know? :)

**Comment by gesellix** [comment]
@rowby did you try the joomla_3_0 branch?

**Comment by gesellix** [comment]
@tripslip38 after a very short test, the titlelink joomla_3_0 branch seems to work, using a fresh joomla-cms install from trunk (joomla 3.1 beta) and with the default sample article.

**Comment by gesellix** [comment]
A Joomla 3.2 compatible download package is available at https://github.com/gesellix-joomla/titlelink/raw/develop/packages/plg_titlelink_2013-11-18_joomla3_2.zip

Please give it a try and in case of issues, please open a new issue at https://github.com/gesellix-joomla/titlelink/issues

Thanks!
