### ISSUE TITLE
Joomla 3.0 article matching error

### ISSUE THREAD

**Issue by tripslip38** [gesellix/titlelink#15]
I installed the current Joomla 3.0 branch tonight, but results weren't as expected. I have an article called "Aircraft Index":

`{ln: Aircraft Index}`

rendered as "administrator-components" which is another article in the system.

**Comment by gesellix** [comment]
did you try without the space after the colon? like this:
`{ln:Aircraft Index}`

**Comment by tripslip38** [comment]
yes, I tried it that way before submitting the bug. 
What's the best way to get debug information? I can can tweak code on the plugin and get some outputs for you.

**Comment by tripslip38** [comment]
If you give me some logging statements to insert, and where to insert them, I can collect some debugging info. I'm not really sure where to start. I've tried `{ln:debug:Aircraft Index}` as well to try to get some debugging info, but it doesn't seem to work.

**Comment by gesellix** [comment]
I'm working on it now, if you like you could enable global debugging in the Joomla global configuration. Then, you might see some sql statements related to titlelink, which you could send me. If they contain sensible data, you can write an email to tobias ät gesellix [dot] de.

**Comment by gesellix** [comment]
can you tell me more details about your article structure? As mentioned in #14 a basic test worked for me.

**Comment by tripslip38** [comment]
Tobias, thanks for working on this today. I am going to do some debugging
tomorrow and will get back to you with some better information.

Thanks,
Zane

**Comment by gesellix** [comment]
@tripslip38 did you have some time investigating?

**Comment by tripslip38** [comment]
Hi Tobias, 

No, I have not tested any further since last we communicated but I plan to soon. I appreciate you checking back in.

-Zane

**Comment by tripslip38** [comment]
Tobias,

I was doing some debugging on this today. I made an article with
{ln:Featured bush planes} but it marks up as "oops not found"

I enabled debugging, and located the query being run by Titlelink. It
appears the parameter is not being inserted into the LIKE string match by
the php. What do you think? I noticed that the query only matches on alias.
Is it required to have alias be just hypen-delimited version of the title?

```SELECT a.id, a.title AS arttitle, a.alias AS artalias, c.id as catid,
c.alias AS catalias
  FROM bcp3jm_content AS a
  LEFT JOIN bcp3jm_categories AS c
  ON a.catid _=_ c.id
  WHERE a.state_=_1
  AND a.alias LIKE '%%' 

```




On Fri, May 3, 2013 at 1:34 PM, Tobias Gesellchen
<notifications@github.com>wrote:

> @tripslip38 <https://github.com/tripslip38> did you have some time
> investigating?
>
> —
> Reply to this email directly or view it on GitHub<https://github.com/gesellix/titlelink/issues/15#issuecomment-17416595>
> .
>
```

**Comment by tripslip38** [comment]
Tobias, did you ever have a chance to investigate this? Kind weird that query not getting the input. I'm on Joomla 3.1.1 now. I tried to trace this but am having trouble with how the phrase gets from the plugin argument to the class.

**Comment by gesellix** [comment]
Hi, I didn't have a chance to investigate, but I'll come back to you asap, probably during the weekend or next week.

**Comment by gesellix** [comment]
Hi,

the queries for my tests show up as follows:

``` sql
SELECT a.id, a.title AS arttitle, a.alias AS artalias, c.id as catid, c.alias AS catalias 
  FROM vjeg4_content AS a 
  LEFT JOIN vjeg4_categories AS c 
  ON a.catid = c.id 
  WHERE a.state=1 
  AND a.alias = 'another article'
SELECT a.id, a.title AS arttitle, a.alias AS artalias, c.id as catid, c.alias AS catalias 
  FROM vjeg4_content AS a 
  LEFT JOIN vjeg4_categories AS c 
  ON a.catid = c.id 
  WHERE a.state=1 
  AND a.title = 'another article'
```

I guess we need more details about your system configuration. Can you collect the following details, please:
- PHP version
- PHP settings and probably PHP information, too
- DB version
- DB collation
  You can find all these details in the Joomla admin backend (System/System information).

As mentioned above: in case there's some sensitive data, just delete them or you might send me the complete details by email.

Thanks!

**Comment by tripslip38** [comment]
Hey Tobias, thanks for replying. I think this is the longest conversation
ever :)

PHP 5.3.10
DB version is Mysql 5.5.31

I've attached the system information html save, without any css or anything
but it looks fine as it's just a table. Open in browser.

Thanks for your help.
Z

On Sat, Jul 13, 2013 at 3:54 AM, Tobias Gesellchen <notifications@github.com

**Comment by gesellix** [comment]
Hi,

looks like the attachment isn't visible. Please try again to send it to tobias @ gesellix . de

Thanks!

**Comment by gesellix** [comment]
Hi,

I don't know if you're still having issues. Could you send me the debug output to the given mail address in my previous comment?

Thanks,
Tobias

**Comment by gesellix** [comment]
A Joomla 3.2 compatible download package is available at https://github.com/gesellix-joomla/titlelink/raw/develop/packages/plg_titlelink_2013-11-18_joomla3_2.zip

Please give it a try and in case of issues, please open a new issue at https://github.com/gesellix-joomla/titlelink/issues

Thanks!

**Comment by tripslip38** [comment]
Tobias, sorry for the super late reply. I started working on something on
the site that brought me back to this.

Your latest version finally works for me. I'm on Joomla 3.1.5. It seems to
be matching article alias only, but it also looks like you have a control
that lets you set the precedence for the article title vs alias matching?

Also, is there a way to avoid having categories prepended to the article
link? I have a situation where my SEF (core joomla) constructs URLs using
the menu structure, but my categories for articles using a matching
hierarchy and I often get a URL like:

knowledge-base/pilots/91-knowledge-base/pilots/163-intro-to-ski-flying

however if I just use knowledge-base/pilots/163-intro-to-ski-flying  that
URL works too, and is preferred.

You can check it out at backcountrypilot.org under the knowledge menu if
you're curious. Anyway, thanks for you help and the great work on this
plugin. Glad it finally works for me, because it's key to using Joomla as a
wiki.

Zane

On Sat, Sep 14, 2013 at 1:25 AM, Tobias Gesellchen <notifications@github.com

**Comment by gesellix** [comment]
Hi Zane,

I'm not sure whether TitleLink is really responsible for the category names in your URL. Internally it should use Joomla methods to transform the most basic URL format to the SEF pattern. TitleLink doesn't handle SEF manually. But maybe TitleLink has to call the Joomla methods another way, though I didn't find an alternative.

You could tell me more details about your SEF configuration, so that I can try to reproduce the problem myself. You're still on PHP 5.3.10 and Mysql 5.5.31?

In other news: I would like to clean this area and move on to the new project home at https://github.com/gesellix-joomla/titlelink
I would ask you to open another issue at the new project home so that I can keep this issue closed.
Thanks!

Tobias
