### ISSUE TITLE
open titlelinks in popup windows

### ISSUE THREAD

**Issue by terrar** [gesellix/titlelink#16]
Would it be possible to get a new feature to open titlelinks in popup windows? (content only) Maybe with the possibility of adjusting this fixed in the config so that existing titlelinks dont have to be rewritten.

**Comment by gesellix** [comment]
do you mean a new window/tab like the html code `target="_blank"` or a real popup?

**Comment by terrar** [comment]
I mean real popups which shwo only the content page of the titlelink.
It would be useful to quickly show informations.

**Comment by gesellix** [comment]
ok, I need to check how to make this as simple as possible, probably with some default configuration in the plugin settings as you already suggested.

**Comment by terrar** [comment]
Time to close ;-)
