### ISSUE TITLE
Titlelink combined with PHP8 crashes Joomla (3.9.25)

### ISSUE THREAD

**Issue by terrar** [gesellix/titlelink#17]
I updated my internal webserver and have now PHP 8.0.3 running.

Since this i get a white Page in Joomla when editing content where titlelink is used.

In an other project i get this error when loading sites with titlelink in use:
count(): Argument #1 ($var) must be of type Countable|array, null given

Disabling the plugin fixes the error.

Is there a solution for it or an update?

**Comment by terrar** [comment]
Ok, project dead? Sad..

**Comment by gesellix** [comment]
Hi @terrar, due to the lack of time I cannot promise any quick fix. If you could manage to submit a pull request with a fix, then I could try to cut a release.

**Comment by gesellix** [comment]
Which Joomla version do you use?

**Comment by terrar** [comment]
I am actually on 3.9.25 (latest release)
With PHP 7.4 there was no error
With PHP 8.0.3 i get "count(): Argument #1 ($var) must be of type Countable|array, null given" or a white screen when editing an article.

I'm afraid I can't deliver a fix due to a lack of programming knowledge in PHP.
Titlelink has been with me for a number of years and is my favorite for internal linking of posts. 
It would be a shame if I had to leave it deactivated.

**Comment by gesellix** [comment]
Now, coming back to this one. I actually made things a little complicated by hosting two different repositories for titlelink here on GitHub. There's another one at https://github.com/gesellix-joomla/titlelink with a change looking like a fix for your error: https://github.com/gesellix-joomla/titlelink/pull/3.

I might have to cut a proper release for Joomla!'s extensions directory, but if you're able to manually edit the titlelink.php, please give it a try. To be more specific: can you try to apply the following [change](https://github.com/gesellix-joomla/titlelink/pull/3/files) to your installed TitleLink plugin?

```diff
            // magix number '2' is the amount of strings we need as result
-            if (count($result) == 2) {
+            if ($result != null && count($result) == 2) {
                return $result;
            }
```

**Comment by terrar** [comment]
> Now, coming back to this one. I actually made things a little complicated by hosting two different repositories for titlelink here on GitHub. There's another one at https://github.com/gesellix-joomla/titlelink with a change looking like a fix for your error: [gesellix-joomla#3](https://github.com/gesellix-joomla/titlelink/pull/3).
> 
> I might have to cut a proper release for Joomla!'s extensions directory, but if you're able to manually edit the titlelink.php, please give it a try. To be more specific: can you try to apply the following [change](https://github.com/gesellix-joomla/titlelink/pull/3/files) to your installed TitleLink plugin?
> 
> ```diff
>             // magix number '2' is the amount of strings we need as result
> -            if (count($result) == 2) {
> +            if ($result != null && count($result) == 2) {
>                 return $result;
>             }
> ```

That did it finally! Works again as expected.
Thank you for your work, really love TitleLink!
Will there come an automatic update via Joomla for this?

**Comment by terrar** [comment]
A little bit too early for state resolved, sorry.
With the patch above i am able to open content with TitleLink in it again, but when making an new link which has no article yet (with existing articles it works) Joomla delivers this:

```
Call stack
--
# | Function | Location
1 | () | JROOT/plugins/system/titlelink/titlelink.php:316
2 | plgSystemTitleLink->replaceTitleLinksWithURLs() | JROOT/plugins/system/titlelink/titlelink.php:118
3 | plgSystemTitleLink->onAfterRender() | JROOT/libraries/joomla/event/event.php:70
4 | JEvent->update() | JROOT/libraries/joomla/event/dispatcher.php:160
5 | JEventDispatcher->trigger() | JROOT/libraries/src/Application/BaseApplication.php:108
6 | Joomla\CMS\Application\BaseApplication->triggerEvent() | JROOT/libraries/src/Application/CMSApplication.php:1096
7 | Joomla\CMS\Application\CMSApplication->render() | JROOT/libraries/src/Application/SiteApplication.php:778
8 | Joomla\CMS\Application\SiteApplication->render() | JROOT/libraries/src/Application/CMSApplication.php:209
9 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/index.php:49
```

**Comment by gesellix** [comment]
@terrar would you mind creating another issue for this?

**Comment by gesellix** [comment]
> Thank you for your work, really love TitleLink!

❤️  😃 

> Will there come an automatic update via Joomla for this?

I can try, but i cannot predict any time range, because I don't use Joomla! anymore. Yet, I see the need to polish and improve the plugin. So, I first have to setup a local dev environment.

**Comment by terrar** [comment]
I switched back to PHP7.4 for the moment, where TitleLink works as expected.
Hope to get an update in the next few months.
best regards

**Comment by gesellix** [comment]
I think that TitleLink works with PHP 8. Have you checked?
