### ISSUE TITLE
Merge gesellix-joomla/titlelink

### ISSUE THREAD

**Issue by hmueller01** [gesellix/titlelink#19]
Hi Tobias,

why don't you merge https://github.com/gesellix-joomla/titlelink into this and drop your own fork? I was a litte confused where to find the latest version ...

And you shouldn't have a directory with packages, instead using the github releases which makes it more convenient to find the released versions ...

Thanks Holger

**Comment by gesellix** [comment]
Please see my comment at https://github.com/gesellix/titlelink/pull/18#issuecomment-1281351141

I'll need some time to clean up - other things are currently more important to me. Yet, I'm going to clean up and then focus on a migration to Joomla 4.x.

**Comment by gesellix** [comment]
The fork has been merged back into this repository.
