### ISSUE TITLE
Make TitleLink compatible with Joomla 4 and Joomla 5

### ISSUE THREAD

**Issue by gesellix** [gesellix/titlelink#22]
- [x] Ensure TitleLink works with Joomla! 4
- [x] Ensure TitleLink works with Joomla! 5
- [x] Support [Joomla!'s update system](https://extensions.joomla.org/support/knowledgebase/item/joomla-update-system-requirement) (the following link seems to work: [joomla-update-system-requirement](https://extensions.joomla.org/support/knowledgebase/submission-requirements/joomla-update-system-requirement/))

**Comment by gesellix** [comment]
The new release 3.8.0 https://github.com/gesellix/titlelink/releases/tag/v3.8.0 should work for Joomla 3.10 as well as Joomla 4.

**Comment by githubteckacom** [comment]
Well, I was very happy to use TiLi in my J4 `s but now we have J5 on the horizon. Are there any plans to update TiLi for J5?

**Comment by gesellix** [comment]
@githubteckacom to me it seems like TitleLink already works with Joomla! 5 without issues. Have you already tried?

**Comment by githubteckacom** [comment]
Oh TKS very much, it works perfect in J5, I tried it *NOW*:-)

**Comment by gesellix** [comment]
The plugin now also supports Joomla!'s Update System. See #24.

**Comment by githubteckacom** [comment]
Hallo Tobias,

hast du irgendwo im Inet-Universum ein DONATE-Button?

lg Tony
--

**Comment by gesellix** [comment]
Hey, das ist nett :)

Du kannst dort schauen: https://github.com/sponsors/gesellix oder auch dort: https://ko-fi.com/gesellix

**Comment by gesellix** [comment]
Danke sehr @githubteckacom!
